### ISSUE TITLE
Windows/linux Version

### ISSUE THREAD

**Issue by Itsamejonah** [darwinx64/LimboKeys#2]
### Why
So more people can use this (linux too)
### How 
Use a similar language to Swift. 

| mac | mac | PC | PC | PC |
| PC | PC | PC | PC | PC |
| PC | PC | PC | PC | PC |
| PC | PC | PC | PC | PC |
| PC | PC | PC | PC | PC | 

PC or Mac: 2000 people

**Comment by darwinx64** [comment]
There are other projects that already support other OSes

https://github.com/ImPavloh/DesktopLimboKeys
https://github.com/quasar098/limbos32

I don't have any interest in developing for other OS at this time.
